apiVersion: v1
kind: ReplicationController
metadata:
  name: general-show
spec:
  selector:
    name: general-show
    version: v0.1-alpha
  template:
    metadata:
      labels:
        name: general-show
	version: v0.1-alpha
    spec:
      containers:
      - name: general-show
        image: jesse/general.show
        ports:
        - containerPort: 80